### ISSUE TITLE
[epic] client: implement smtp.Transport as an analogy to net/http.Transport

### ISSUE THREAD

**Issue by kayrus** [emersion/go-smtp#154]
Current SMTP client implementation is not optimal. It acts like HTTP/1.0: one request per connection.
I'd like to see an SMTP client, which will have an SMTP transport by an analogy to `http.Client` and `http.Transport`.

Transport should allow to perform a `RoundTripper` method, reuse idle connections, have a map of connections per host, efficiently reuse established AUTH sessions to send messages within the ​same auth session when possible, etc.

P.S. I know this is a big task, and  it will require a lot of effort. But at the end it will give a similar flexibility as `net/http` package give. I appreciate objections, feedback, suggestions.

Reference https://github.com/emersion/go-smtp-proxy/issues/9

**Comment by emersion** [comment]
> It acts like HTTP/1.0: one request per connection.

Nothing stops you from sending multiple messages with a single `Client`.

HTTP is also a bit different because it's stateless. SMTP is stateful.

Even if this was possible, I'm not sure I like the added complexity.

**Comment by foxcpp** [comment]
Connection pooling is non-trivial due to SMTP stateful nature.  I believe this is something that is best implemented by library users taking into consideration what is important for their own implementation.

FWIW, here is how connection pooling for MX is implemented in maddy:
* https://github.com/foxcpp/maddy/blob/master/internal/smtpconn/pool/pool.go
* https://github.com/foxcpp/maddy/blob/master/internal/target/remote/connect.go#L56-L61

Note that it does not manage authentication in any way.

**Comment by emersion** [comment]
Closing because I think this is out of scope.
